theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.follow
    - content.code.copy
    - navigation.top
  palette:
    primary: indigo  # 可选：添加主题颜色
  language: zh
  
site_url: https://zhiweinju.github.io/nju-dl-lab-2025spring/

extra_css:
  - https://fonts.loli.net/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&display=swap
  - https://cdn.bootcdn.net/ajax/libs/lxgw-wenkai-screen-webfont/1.7.0/style.min.css
  - https://fonts.loli.net/css2?family=Noto+Serif+SC&display=swap
  - css/custom.css

site_name: 深度学习平台和应用（2025春）
nav:
  - 主页: "index.md"
  - 实验一: 
    - 1.1 实验说明: "lab1/实验一介绍.md"
    - 1.2 实验任务一：环境配置: "lab1/环境配置指南.md"
    - 1.3 实验任务二：PyTorch练习: "lab1/实验一代码.md"
  - 实验二:
    - 2.1 实验说明: "lab2/实验二介绍.md"
    - 2.2 实验任务一：MINIST手写数字识别: "lab2/MINIST手写数字识别.md"
    - 2.3 实验任务二：正则化和激活函数探索: "lab2/正则化和激活函数探索.md"
  - 实验三:
    - 3.1 实验说明: "lab3/实验三介绍.md"
    - 3.2 实验任务一：图像卷积: "lab3/图像卷积.md"
    - 3.3 实验任务二：CNN图像分类: "lab3/CNN图像分类.md"
  - 实验四:
    - 4.1 实验说明: "lab4/实验四介绍.md"
    - 4.2 实验任务一：词嵌入: "lab4/词嵌入.md"
    - 4.3 实验任务二：RNN文本生成: "lab4/RNN文本生成汇总.md"
  - 实验五:
      - 5.1 实验说明: "lab5/实验五介绍.md"
      - 5.2 实验任务一：Transformer: "lab5/transformer.md"
      - 5.3 实验任务二：预训练语言模型: "lab5/预训练语言模型.md"
  - 实验六:
      - 6.1 实验说明: "lab6/实验六介绍.md"
      - 6.2 实验任务一：GAN: "lab6/实验任务一：生成对抗网络（GAN）.md"
      - 6.3 实验任务二：DCGAN: "lab6/实验任务二：深度卷积生成对抗网络（DCGAN）.md"
      - 6.4 实验任务三：WGAN: "lab6/实验任务三：WGAN.md"
      



markdown_extensions:
  - toc:
      permalink: True
  - footnotes
  - tables
  - admonition  # 提示块
  - pymdownx.details  # 提示块可折叠
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - attr_list  # 支持添加属性
  - pymdownx.arithmatex:  # 添加数学公式支持
      generic: true

# extra:
#   consent:
#     actions:
#       - download

extra_javascript:  # 添加 MathJax 支持
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
